/**
 * Standard disclaimer block.
 *
 * MUST appear in every rendered artifact (PDF + CSV). Renderers receive a
 * DisclaimerContext and call buildDisclaimer() to get the final text.
 * If the disclaimer is absent from an artifact, the content-assertion test fails.
 *
 * Rule: no figure leaves the platform without this block. Presigned URL =
 * file outlives session + auth; in-document disclaimer is what makes 7-day
 * link exposure acceptable.
 */

export interface DisclaimerContext {
  engineVersion: string;
  rulesetVersion: string;
  rulesetStatus: string;
  generatedAt: string;
  reportId: string;
  templateSlug: string;
  templateVersion: string;
}

export const DISCLAIMER_SENTINEL = 'EQUITYLENS_DISCLAIMER';

export function buildDisclaimerText(ctx: DisclaimerContext): string {
  return `This report is generated by EquityLens Pty Ltd ("EquityLens"). It is general information only, does not take into account your personal circumstances, and does not constitute financial, taxation, legal, or investment advice. Figures are estimates produced by a software model based on inputs provided by you and the tax ruleset version stated below; they may differ from amounts ultimately assessed by the Australian Taxation Office, State Revenue Office of Victoria, or other authorities. You should consult a registered tax agent, financial adviser, or solicitor before making decisions. EquityLens does not guarantee the accuracy, completeness, or currency of any figure herein.

Ruleset: ${ctx.rulesetVersion} (${ctx.rulesetStatus}) | Engine: ${ctx.engineVersion}
Generated: ${ctx.generatedAt} | Report ID: ${ctx.reportId}
Template: ${ctx.templateSlug}@${ctx.templateVersion}`;
}

/**
 * CSV disclaimer block — prefixed with # so most parsers treat it as comments,
 * but the sentinel string is present so content-assertion tests can detect it.
 */
export function buildCsvDisclaimerLines(ctx: DisclaimerContext): string {
  const text = buildDisclaimerText(ctx);
  return text
    .split('\n')
    .map((line) => `# ${line}`)
    .join('\r\n');
}
