'use client';

import { useState } from 'react';

import type { Explanation } from '@/server/ai/gateway';

// ── D11-T5 badge note ─────────────────────────────────────────────────────────
// This component inherits the ProvisionalWarning framing from the result page.
// The badge label "AI estimate · FY2026 draft rules" makes the double-provisional
// nature explicit: draft rules + model-generated = doubly uncertain.
// The badge is always shown; it cannot be suppressed by the user.

interface Props {
  scenarioId: string;
}

type State =
  | { phase: 'idle' }
  | { phase: 'loading' }
  | { phase: 'suppressed'; reason: 'grounding_fail' | 'pii_tfn' | string }
  | { phase: 'done'; explanation: Explanation }
  | { phase: 'error'; message: string };

export function AiExplanation({ scenarioId }: Props) {
  const [state, setState] = useState<State>({ phase: 'idle' });

  async function requestExplanation() {
    setState({ phase: 'loading' });
    try {
      const res = await fetch(`/api/scenarios/${scenarioId}/explain`, { method: 'POST' });
      const body = (await res.json().catch(() => ({}))) as Record<string, unknown>;

      if (!res.ok) {
        setState({
          phase: 'error',
          message: (body['error'] as string | undefined) ?? 'Failed to generate explanation.',
        });
        return;
      }

      if (body['suppressed']) {
        setState({
          phase: 'suppressed',
          reason: (body['reason'] as string | undefined) ?? 'unknown',
        });
        return;
      }

      setState({ phase: 'done', explanation: body['explanation'] as Explanation });
    } catch {
      setState({ phase: 'error', message: 'Something went wrong. Please try again.' });
    }
  }

  // ── Idle: prompt the user to generate ────────────────────────────────────

  if (state.phase === 'idle') {
    return (
      <div className="flex flex-col gap-[var(--space-3)]">
        <div className="flex items-center gap-[var(--space-2)]">
          <span className="rounded-full bg-[var(--bg-muted)] px-[var(--space-2)] py-[var(--space-1)] [font-size:var(--text-xs)] text-[var(--fg-muted)]">
            AI estimate · FY2026 draft rules
          </span>
        </div>
        <p className="[font-size:var(--text-sm)] text-[var(--fg-muted)]">
          Get a plain-English explanation of this CGT calculation, generated by Claude under the
          draft FY2026 ruleset. This is an AI-generated estimate and must not be relied upon for tax
          decisions.
        </p>
        <button
          onClick={requestExplanation}
          className="self-start rounded-[var(--radius-md)] border border-[var(--border-default)] bg-[var(--bg-surface)] px-[var(--space-4)] py-[var(--space-2)] [font-size:var(--text-sm)] text-[var(--fg-default)] hover:bg-[var(--bg-muted)]"
        >
          Generate explanation
        </button>
      </div>
    );
  }

  // ── Loading ───────────────────────────────────────────────────────────────

  if (state.phase === 'loading') {
    return (
      <div className="flex items-center gap-[var(--space-2)] [font-size:var(--text-sm)] text-[var(--fg-muted)]">
        <span className="rounded-full bg-[var(--bg-muted)] px-[var(--space-2)] py-[var(--space-1)] [font-size:var(--text-xs)]">
          AI estimate · FY2026 draft rules
        </span>
        Generating…
      </div>
    );
  }

  // ── Suppressed: grounding failed or TFN detected ──────────────────────────

  if (state.phase === 'suppressed') {
    const message =
      state.reason === 'pii_tfn'
        ? 'Explanation unavailable — sensitive information detected in the scenario context.'
        : 'Explanation unavailable — the generated content could not be verified against the engine result.';
    return (
      <div className="flex items-start gap-[var(--space-2)]">
        <span className="rounded-full bg-[var(--bg-muted)] px-[var(--space-2)] py-[var(--space-1)] [font-size:var(--text-xs)] text-[var(--fg-muted)]">
          AI estimate · FY2026 draft rules
        </span>
        <p className="[font-size:var(--text-sm)] text-[var(--fg-muted)]">{message}</p>
      </div>
    );
  }

  // ── Error ─────────────────────────────────────────────────────────────────

  if (state.phase === 'error') {
    return (
      <div className="flex flex-col gap-[var(--space-2)]">
        <span className="self-start rounded-full bg-[var(--bg-muted)] px-[var(--space-2)] py-[var(--space-1)] [font-size:var(--text-xs)] text-[var(--fg-muted)]">
          AI estimate · FY2026 draft rules
        </span>
        <p className="[font-size:var(--text-sm)] text-[var(--fg-muted)]">{state.message}</p>
        <button
          onClick={requestExplanation}
          className="self-start [font-size:var(--text-xs)] text-[var(--fg-muted)] hover:underline"
        >
          Try again
        </button>
      </div>
    );
  }

  // ── Done: render explanation ──────────────────────────────────────────────

  const { explanation } = state;

  return (
    <div className="flex flex-col gap-[var(--space-4)]">
      {/* Badge — always shown, doubly provisional */}
      <span className="self-start rounded-full bg-[var(--bg-muted)] px-[var(--space-2)] py-[var(--space-1)] [font-size:var(--text-xs)] text-[var(--fg-muted)]">
        AI estimate · FY2026 draft rules
      </span>

      {/* Summary paragraph */}
      <p className="[font-size:var(--text-sm)] text-[var(--fg-default)]">{explanation.summary}</p>

      {/* Key figures */}
      {explanation.items.length > 0 && (
        <div className="divide-y divide-[var(--border-muted)]">
          {explanation.items.map((item, i) => (
            <div key={i} className="flex items-start justify-between py-[var(--space-2)]">
              <div>
                <span className="[font-size:var(--text-sm)] text-[var(--fg-muted)]">
                  {item.label}
                </span>
                {item.note && (
                  <p className="[font-size:var(--text-xs)] text-[var(--fg-subtle)]">{item.note}</p>
                )}
              </div>
              <span className="[font-size:var(--text-sm)] tabular-nums text-[var(--fg-default)]">
                {item.value}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* Disclaimer — always shown */}
      <p className="[font-size:var(--text-xs)] text-[var(--fg-muted)]">{explanation.disclaimer}</p>
    </div>
  );
}
