-- =============================================================================
-- Migration 0005 — report_jobs v2: idempotency + queue fields + presigned URL
-- =============================================================================
-- Extends the baseline report_jobs table (0001) with the columns needed for
-- the Day 12 export pipeline:
--   • idempotency_key  — unique per (tenant, template, format, scope hash);
--                        prevents duplicate jobs on network retry
--   • queue_name       — 'exports.fast' | 'exports.bulk' (Upstash QStash)
--   • org_id           — tenant scope; required for RLS and idempotency key
--   • artifact_key     — Supabase Storage object key once upload completes
--   • presigned_url    — signed download URL (7-day TTL, generated post-upload)
--   • presigned_url_expires_at — UTC timestamp of URL expiry
--   • output_hash      — SHA-256 of the rendered artifact bytes (idempotency
--                        verify: same inputs → same hash)
-- Status values aligned to the worker state machine:
--   queued → running → succeeded | failed
-- (The baseline used 'pending'/'completed'; renamed for clarity. Old rows
--  with 'pending'/'completed' are migrated in-place below.)
-- =============================================================================

-- Rename status values from baseline to new names
UPDATE report_jobs SET status = 'queued'    WHERE status = 'pending';
UPDATE report_jobs SET status = 'succeeded' WHERE status = 'completed';

-- Drop old status constraint, add new one
ALTER TABLE report_jobs DROP CONSTRAINT IF EXISTS report_jobs_status_check;
ALTER TABLE report_jobs
  ADD CONSTRAINT report_jobs_status_check
  CHECK (status IN ('queued', 'running', 'succeeded', 'failed'));

-- New columns
ALTER TABLE report_jobs
  ADD COLUMN IF NOT EXISTS org_id                   UUID,
  ADD COLUMN IF NOT EXISTS idempotency_key          TEXT,
  ADD COLUMN IF NOT EXISTS queue_name               TEXT CHECK (queue_name IN ('exports.fast', 'exports.bulk')),
  ADD COLUMN IF NOT EXISTS artifact_key             TEXT,
  ADD COLUMN IF NOT EXISTS presigned_url            TEXT,
  ADD COLUMN IF NOT EXISTS presigned_url_expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS output_hash              TEXT;

-- Unique constraint on idempotency_key (duplicate submissions return existing job)
CREATE UNIQUE INDEX IF NOT EXISTS idx_report_jobs_idempotency
  ON report_jobs(idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- Index for org-scoped listing
CREATE INDEX IF NOT EXISTS idx_report_jobs_org
  ON report_jobs(org_id, requested_at DESC)
  WHERE org_id IS NOT NULL;

COMMENT ON TABLE report_jobs IS
  'Export job queue. APPEND-ONLY after insert; status transitions via worker.';
COMMENT ON COLUMN report_jobs.idempotency_key IS
  'SHA-256 of (org_id, template_id, format, scope JSON, ruleset_version). Duplicate submissions return the same job.';
COMMENT ON COLUMN report_jobs.presigned_url IS
  'Supabase Storage signed URL (7-day TTL). Regenerated by GET /api/exports/[id] if expired.';
COMMENT ON COLUMN report_jobs.output_hash IS
  'SHA-256 of rendered artifact bytes. Same inputs must produce same hash across reruns.';
